### ISSUE TITLE
Comments on items not being sent in email to Supplier

### ISSUE THREAD

**Issue by elbrando** [ShoppinPal/StockUp#470]
In StockUp, comments are not making it into the email that the Supplier gets even though they were done properly and exist in StockUp. See attachments

![71st-LCD-Dancewear-order-10-8-2020-no-comments](https://user-images.githubusercontent.com/10925748/95481969-3d480e00-0953-11eb-9cd6-864bc1da1f4b.png)

![71st-LCD-Dancewear-order-10-8-2020-in-StockUp-with-comments](https://user-images.githubusercontent.com/10925748/95482067-5650bf00-0953-11eb-8b62-4dff633ed48f.png)

**Comment by kamal0808** [comment]
Fixed in #472 
<img width="970" alt="Screen Shot 2020-10-12 at 4 07 12 PM" src="https://user-images.githubusercontent.com/15616412/95737110-cee1b380-0ca4-11eb-93eb-d835381914b4.png">
![Screen Shot 2020-10-12 at 3 56 54 PM](https://user-images.githubusercontent.com/15616412/95737124-d2753a80-0ca4-11eb-993e-3457a44c97be.png)
![Screen Shot 2020-10-12 at 4 07 41 PM](https://user-images.githubusercontent.com/15616412/95737149-ddc86600-0ca4-11eb-9ae4-11fa9ee85261.png)
